### ISSUE TITLE
Using the hotkey to start a verb makes the verb lose its slot upon completion, ejecting the verb's products. 

### ISSUE THREAD

**Issue by Technotoad64** [weatherfactory/cultistsimulator-visible#18] opened 2022-03-03 23:38 UTC
Appears to only happen when using the same hotkey to start verbs and collect their results, which wasn't causing any issues before the 3-3-22 update.

**Comment by Technotoad64** [comment] 2022-03-03 23:39
The issue remains even after relaunching, so doing this even once can lead to softlock, since the verb becomes unusable.

**Comment by alexiskennedy** [comment] 2022-03-04 13:39
Aha. This only happens if you've reassigned the hotkeys to be the same, e.g. C for both Start and Collect, right?

It's a bug that you assign the same hotkey to both, but if people are doing this intentionally, maybe I should support it. Thoughts?

**Comment by alexiskennedy** [comment] 2022-03-06 17:32
Fixed (by making ConcludeCommand() obsolete in Ongoing as well as Unstarted). But it's caused by an underlying oddity where a keyboard command can trigger multiple effects, which I don't want.

**Comment by alexiskennedy** [comment] 2022-03-06 17:50
Collect & Start now only trigger on UnityInputPhase.Started

**Closed by alexiskennedy** 2022-03-06 17:50 UTC
Labels: pri:4
