### ISSUE TITLE
Placement of cards often leave their ghost on the table

### ISSUE THREAD

**Issue by Genroa** [weatherfactory/cultistsimulator-visible#11] opened 2022-03-01 11:23 UTC
Branch: beta branch (gateofhorn)

Behavior: cards, when dropped, often leave their ghost in place. The displayed ghost also isn't the actual position of the card and can be very far from it if you play a bit around bit areas (like the card's tray).

Here is a picture of the behavior: 
![image](https://user-images.githubusercontent.com/4357574/156160617-24b77539-f3c9-4827-b698-bef61af2543a.png)

(none of these cards is currently being held)

**Comment by alexiskennedy** [comment] 2022-03-01 13:31
I've tried to repro this and can't. It may be related to #10, which is fixed in 2022.3.a.1 . If you're still seeing it in this patch, can you do me a quick video? ta!

**Comment by Genroa** [comment] 2022-03-01 16:31
I am reproducing this on the latest unmodded beta version. Here is a short vidéo recording the behavior:
[https://www.youtube.com/watch?v=cdb045oYAUY](https://www.youtube.com/watch?v=cdb045oYAUY
)

Since you do not reproduce any of the two bugs I've reported, maybe the latest build didn't hit Steam yet? I don't know exactly how it works on your side.

**Comment by alexiskennedy** [comment] 2022-03-02 10:37
> I don't know exactly how it works on your side.

A build script produces each of the three OS versions of the game; another build script preps them for distribution on each of the three storefronts; two more store-specific upload scripts (and a zip file upload because Humble is more primitive) upload them to the storefronts. Sometimes one of those hiccups, and sometimes the client hiccups so the user doesn't have the latest version. This is why I'm always so keen to confirm the version number - which you've obligingly provided on the video, ta!

And interestingly I can now reproduce this issue trivially on my installed Steam version, so something's got out of sync. Thanks for the heads-up; hold tight.

**Closed** 2022-03-02 16:07 UTC
Labels: more-info-pls
