### ISSUE TITLE
Decks can't have multiple tokens of the same element - breaks deck probabilities

### ISSUE THREAD

**Issue by Chelnoque** [weatherfactory/cultistsimulator-visible#137] opened 2022-06-04 10:11 UTC
When shuffling a deck, it shuffles in *only one instance of each unique element* in the deck spec.

"spec [ dread, dread, dread ]" equals "spec [ dread ]"

Easy to confirm by the first season draw - the shuffle log will report 7 cards in the resulting deck:

\>>>>>>>> EXECUTING: drawseason
\>>>>>>>> Shuffling seasonevents. 7 cards available to shuffle.

But original seasonevents deck consists of 11 cards.

This happens because of the usage of Linq.Except() method in Dealer.Shuffle(). Except() returns only unique entries from the first collection. Using a simple foreach will solve the issue.

**Comment by ClocQ** [comment] 2022-06-04 10:41
Hi.

I am assuming that #130 is caused by the same factors, what do you think?

**Comment by Chelnoque** [comment] 2022-06-04 11:11
Hi! Almost certainly it is.

**Comment by ClocQ** [comment] 2022-06-04 11:21
Thank you very much.
I was worried that it was just an issue with my environment, as no one else had pointed out that the play feel should obviously be different from the 2021 version.
I'm relieved to know that's not the case :)

**Comment by alexiskennedy** [comment] 2022-06-06 15:41
Well hot dang. Excellent catch. Thank you both very much. Fixed in BRYONY.

**Closed by alexiskennedy** 2022-06-06 15:41 UTC
